# Generated by Django 5.0.14 on 2025-12-13 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("civic_saathi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="current_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="civic_saathi.officer",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="current_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_work",
                to="civic_saathi.worker",
            ),
        ),
        migrations.AlterField(
            model_name="complaintlog",
            name="new_dept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_logs",
                to="civic_saathi.department",
            ),
        ),
        migrations.AlterField(
            model_name="complaintlog",
            name="old_dept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_logs",
                to="civic_saathi.department",
            ),
        ),
        migrations.AlterField(
            model_name="officer",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="civic_saathi.department",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="civic_saathi.department",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ComplaintCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="civic_saathi.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="complaint",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="civic_saathi.complaintcategory",
            ),
        ),
    ]
