# Generated by Django 5.0.14 on 2025-12-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("civic_saathi", "0002_alter_complaint_current_officer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="1=Normal, 2=High, 3=Critical"
            ),
        ),
        migrations.CreateModel(
            name="ComplaintEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("escalated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="civic_saathi.complaint",
                    ),
                ),
                (
                    "escalated_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalated_from",
                        to="civic_saathi.officer",
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalated_to",
                        to="civic_saathi.officer",
                    ),
                ),
            ],
        ),
    ]
