# Generated by Django 5.0.14 on 2025-12-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("civic_saathi", "0003_complaint_priority_complaintescalation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("public_toilet", "Public Toilet"),
                            ("govt_building", "Government Building"),
                            ("park", "Park"),
                            ("bus_stop", "Bus Stop"),
                            ("streetlight_zone", "Streetlight Zone"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.TextField()),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facilities",
                        to="civic_saathi.worker",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="civic_saathi.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="FacilityInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_date", models.DateTimeField(auto_now_add=True)),
                (
                    "cleanliness_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "functional_status",
                    models.BooleanField(
                        default=True, help_text="Is facility functional?"
                    ),
                ),
                ("issues_found", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="inspections/"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="civic_saathi.facility",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="civic_saathi.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="SLAConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution_hours",
                    models.PositiveIntegerField(
                        default=48, help_text="Hours to resolve before escalation"
                    ),
                ),
                (
                    "escalation_hours",
                    models.PositiveIntegerField(
                        default=72,
                        help_text="Hours before escalating to senior officer",
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla",
                        to="civic_saathi.complaintcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Streetlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pole_id", models.CharField(max_length=50, unique=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("ward", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("functional", "Functional"),
                            ("non_functional", "Non-Functional"),
                            ("under_repair", "Under Repair"),
                        ],
                        default="functional",
                        max_length=20,
                    ),
                ),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="civic_saathi.worker",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streetlights",
                        to="civic_saathi.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                            ("on_leave", "On Leave"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="civic_saathi.worker",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Worker Attendance",
                "ordering": ["-date"],
                "unique_together": {("worker", "date")},
            },
        ),
    ]
