# Generated by Django 5.0.14 on 2025-12-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "civic_saathi",
            "0004_facility_facilityinspection_slaconfig_streetlight_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="civic_saathi.complaintcategory",
            ),
        ),
    ]
