# Generated by Django 5.0.14 on 2025-12-13 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("civic_saathi", "0005_alter_complaint_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cleanliness_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "⭐ Very Poor"),
                            (2, "⭐⭐ Poor"),
                            (3, "⭐⭐⭐ Average"),
                            (4, "⭐⭐⭐⭐ Good"),
                            (5, "⭐⭐⭐⭐⭐ Excellent"),
                        ]
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional feedback"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="facility_ratings/"
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Verified by staff"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_ratings",
                        to="civic_saathi.facility",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Rating",
                "verbose_name_plural": "Public Ratings",
                "ordering": ["-created_at"],
            },
        ),
    ]
