"""
Django settings for municipal project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-&17c1m9pobb7yydwl$3hsn63ay#(#%bz#1znkg5rt!1kuotwmq")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = [
    "https://web-production-c64de.up.railway.app",
    "https://*.railway.app",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]


# Application definition

INSTALLED_APPS = [
    "civic_saathi",
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "rest_framework",
    "rest_framework.authtoken",  # Add this for token auth
    "corsheaders",  # CORS headers
    "django.contrib.staticfiles",
    "django_extensions",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Must be at the top
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "civic_saathi.middleware.AutoStaffPermissionsMiddleware",  # Auto-assign permissions to staff
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://civicsaathi.vercel.app",  # Add your production frontend URL when deployed
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

ROOT_URLCONF = "municipal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "municipal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Use SQLite locally, PostgreSQL on Railway
import dj_database_url

USE_SQLITE = os.environ.get("USE_SQLITE", "False").lower() in ("true", "1", "yes")

if USE_SQLITE or not os.environ.get("DATABASE_URL"):
    # Local development with SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
elif os.environ.get("DATABASE_URL"):
    # Railway production with PostgreSQL
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ.get("DATABASE_URL"),
            conn_max_age=600,
        )
    }
else:
    # Fallback PostgreSQL config
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("PGDATABASE", "railway"),
            "USER": os.environ.get("PGUSER", "postgres"),
            "PASSWORD": os.environ.get("PGPASSWORD", ""),
            "HOST": os.environ.get("PGHOST", os.environ.get("RAILWAY_PRIVATE_DOMAIN", "localhost")),
            "PORT": os.environ.get("PGPORT", "5432"),
            "OPTIONS": {
                "sslmode": os.environ.get("PGSSLMODE", "allow"),
            },
            "CONN_MAX_AGE": 600,
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# ========================================
# JAZZMIN ADMIN UI CONFIGURATION
# ========================================
JAZZMIN_SETTINGS = {
    # Title
    "site_title": "Municipal Admin",
    "site_header": "🏛️ Municipal Governance",
    "site_brand": "Civic Saathi",
    "welcome_sign": "Welcome to Municipal Governance Portal",
    "copyright": "Municipal Corporation",

    # Search models from sidebar
    "search_model": ["civic_saathi.Complaint", "civic_saathi.Worker", "civic_saathi.Streetlight"],

    # User avatar
    "user_avatar": None,

    # Top Menu Links
    "topmenu_links": [
        {"name": "🏠 Home", "url": "admin:index"},
        {"name": "📊 Complaints", "url": "admin:civic_saathi_complaint_changelist"},
        {"name": "👷 Workers", "url": "admin:civic_saathi_worker_changelist"},
        {"name": "📋 Attendance", "url": "admin:civic_saathi_workerattendance_changelist"},
    ],

    # Sidebar - ORGANIZED BY FUNCTION
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["auth"],  # Hide auth, we'll add it manually
    "hide_models": ["civic_saathi.Assignment", "civic_saathi.ComplaintLog"],

    # Custom icons for apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "civic_saathi.Department": "fas fa-building",
        "civic_saathi.Officer": "fas fa-user-tie",
        "civic_saathi.Worker": "fas fa-hard-hat",
        "civic_saathi.Complaint": "fas fa-exclamation-triangle",
        "civic_saathi.ComplaintCategory": "fas fa-tags",
        "civic_saathi.ComplaintLog": "fas fa-history",
        "civic_saathi.ComplaintEscalation": "fas fa-level-up-alt",
        "civic_saathi.Assignment": "fas fa-tasks",
        "civic_saathi.WorkerAttendance": "fas fa-calendar-check",
        "civic_saathi.Facility": "fas fa-restroom",
        "civic_saathi.FacilityInspection": "fas fa-clipboard-check",
        "civic_saathi.SLAConfig": "fas fa-clock",
        "civic_saathi.Streetlight": "fas fa-lightbulb",
    },

    # Model ordering - GROUPED LOGICALLY
    "order_with_respect_to": [
        "civic_saathi",
        # Complaints Section
        "civic_saathi.Complaint",
        "civic_saathi.ComplaintEscalation",
        "civic_saathi.ComplaintCategory",
        "civic_saathi.SLAConfig",
        # People Section  
        "civic_saathi.Officer",
        "civic_saathi.Worker",
        "civic_saathi.WorkerAttendance",
        # Assets Section
        "civic_saathi.Facility",
        "civic_saathi.FacilityInspection",
        "civic_saathi.Streetlight",
        # Admin Section
        "civic_saathi.Department",
        "auth",
    ],

    # Custom sidebar links - TREE STRUCTURE
    "custom_links": {
        "civic_saathi": [
            {
                "name": "📊 Dashboard Overview",
                "url": "admin:index",
                "icon": "fas fa-tachometer-alt",
            },
            {
                "name": "🔥 Pending Complaints",
                "url": "admin:civic_saathi_complaint_changelist",
                "icon": "fas fa-fire text-danger",
            },
            {
                "name": "⚡ Escalated Issues",
                "url": "admin:civic_saathi_complaintescalation_changelist",
                "icon": "fas fa-arrow-up text-warning",
            },
            {
                "name": "👤 User Management",
                "url": "admin:auth_user_changelist",
                "icon": "fas fa-users-cog",
                "permissions": ["auth.view_user"]
            },
        ]
    },

    # Related Modal
    "related_modal_active": True,

    # UI Tweaks
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,

    # Change view - Horizontal tabs for better organization
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "civic_saathi.complaint": "horizontal_tabs",
        "civic_saathi.facility": "horizontal_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark navbar-success",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True,
}


# ========================================
# EMAIL CONFIGURATION
# ========================================
# Using Gmail SMTP
# 
# IMPORTANT: Gmail requires "App Password" instead of regular password!
# Steps to generate App Password:
# 1. Go to https://myaccount.google.com/security
# 2. Enable 2-Step Verification (if not already)
# 3. Go to "App passwords" (search in security settings)
# 4. Generate a new app password for "Mail" and "Windows Computer"
# 5. Use that 16-character password below (or in EMAIL_HOST_PASSWORD env var)
#
# For development/testing, uncomment the console backend line below:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'akshatjain1678@gmail.com')
# Replace 'arya@123' with your Gmail App Password (16 chars, no spaces)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'onorxjsblaozjbte')  # App Password
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Municipal Portal <akshatjain1678@gmail.com>')


# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

