"""
Django settings for municipal project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-&17c1m9pobb7yydwl$3hsn63ay#(#%bz#1znkg5rt!1kuotwmq")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "civic_saathi",
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "rest_framework",
    "django.contrib.staticfiles",
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "municipal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "municipal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("PGDATABASE", "postgres"),
        "USER": os.environ.get("PGUSER", "postgres"),
        "PASSWORD": os.environ.get("PGPASSWORD", ""),
        "HOST": os.environ.get("PGHOST", "localhost"),
        "PORT": os.environ.get("PGPORT", "5432"),
        "OPTIONS": {
            "sslmode": os.environ.get("PGSSLMODE", "allow"),
        },
        "CONN_MAX_AGE": 600,
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# ========================================
# JAZZMIN ADMIN UI CONFIGURATION
# ========================================
JAZZMIN_SETTINGS = {
    # Title
    "site_title": "Municipal Admin",
    "site_header": "Municipal Governance",
    "site_brand": "Civic Saathi",
    "welcome_sign": "Welcome to Municipal Governance Portal",
    "copyright": "Municipal Corporation",

    # Logo (optional - add your logo to static/img/)
    # "site_logo": "img/logo.png",

    # User avatar
    "user_avatar": None,

    # Top Menu Links
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Dashboard", "url": "admin:index"},
        {"app": "civic_saathi"},
    ],

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Custom icons for apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "civic_saathi.Department": "fas fa-building",
        "civic_saathi.Officer": "fas fa-user-tie",
        "civic_saathi.Worker": "fas fa-hard-hat",
        "civic_saathi.Complaint": "fas fa-exclamation-triangle",
        "civic_saathi.ComplaintCategory": "fas fa-tags",
        "civic_saathi.ComplaintLog": "fas fa-history",
        "civic_saathi.ComplaintEscalation": "fas fa-level-up-alt",
        "civic_saathi.Assignment": "fas fa-tasks",
        "civic_saathi.WorkerAttendance": "fas fa-calendar-check",
        "civic_saathi.Facility": "fas fa-restroom",
        "civic_saathi.FacilityInspection": "fas fa-clipboard-check",
        "civic_saathi.SLAConfig": "fas fa-clock",
        "civic_saathi.Streetlight": "fas fa-lightbulb",
    },

    # Model ordering within app
    "order_with_respect_to": [
        "civic_saathi",
        "civic_saathi.Complaint",
        "civic_saathi.ComplaintEscalation",
        "civic_saathi.WorkerAttendance",
        "civic_saathi.Facility",
        "civic_saathi.FacilityInspection",
        "civic_saathi.Streetlight",
        "civic_saathi.Department",
        "civic_saathi.Officer",
        "civic_saathi.Worker",
        "civic_saathi.ComplaintCategory",
        "civic_saathi.SLAConfig",
        "auth",
    ],

    # Custom Links in sidebar
    "custom_links": {
        "civic_saathi": [
            {
                "name": "Overdue Complaints",
                "url": "admin:civic_saathi_complaint_changelist",
                "icon": "fas fa-fire",
                "permissions": ["civic_saathi.view_complaint"]
            },
        ]
    },

    # Related Modal
    "related_modal_active": True,

    # UI Tweaks
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,

    # Change view
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "civic_saathi.complaint": "horizontal_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark navbar-success",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True,
}

